spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/springsecurityrest
    username: user
    password: jLu0XC#GP8sQO+LP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: '/api'

server:
  port: 3000
  address: localhost

purge:
  cron:
    expression: 0 0 5 * * ?