spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/huisapp
    username: arman
    password: Ddk24*9#qzn@HTyP0X
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 3000
  address: localhost